# Use an official PHP image that includes the Apache Web Server
FROM php:8.2-apache

# Install necessary system libraries and PHP extensions for Symfony
RUN apt-get update && apt-get install -y libzip-dev unzip libpq-dev postgresql-client && docker-php-ext-install pdo pdo_mysql zip pdo_pgsql

# Install Composer (the PHP package manager)
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Set the working directory for our website
WORKDIR /var/www/html

# Copy the website files from our repository into the container
COPY . .

# Create a .env file for production build scripts
RUN echo "APP_ENV=prod\nDATABASE_URL=postgres://user:pass@example.com:5432/db" > .env

# Allow composer to run as root with plugins
ENV COMPOSER_ALLOW_SUPERUSER=1

# Install dependencies and run scripts
RUN composer install --no-dev --optimize-autoloader

# Set the correct file permissions for Symfony's cache/log folders
RUN chown -R www-data:www-data var

# Expose the correct port
EXPOSE 80