services:
  - type: web
    name: portfolio
    runtime: php
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: false
      - key: APP_SECRET
        generateValue: true
