<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPkmBYAN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPkmBYAN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPkmBYAN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPkmBYAN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPkmBYAN\App_KernelDevDebugContainer([
    'container.build_hash' => 'PkmBYAN',
    'container.build_id' => '4d9cfd5e',
    'container.build_time' => 1742550089,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPkmBYAN');
